apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deploy
  labels:
    app: back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      name: backend-pod
      labels:
        app: back
    spec:
      containers:
        - name: backend
          image: bakhtawar375/w-backend
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: back
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      nodePort: 30500

