apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deploy
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      name: front-pod
      labels:
        app: front
    spec:
      containers:
        - name: frontend
          image: bakhtawar375/w-frontend
          ports:
            - containerPort: 5173

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: front
  ports:
    - port: 5173
      targetPort: 5173
      protocol: TCP
      nodePort: 30173
